name: Check

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - example/**
      - "**/*.md"
      - "**/*.yaml"
  push:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: 🚬 Smoke Test
        run: |
          go build ./...
          ./m3u8-downloader -version | grep -q 'm3u8-downloader' || exit 1
      # - name: 🧹 Lint
      #   uses: golangci/golangci-lint-action@v6
      #   with:
      #     version: latest
      #     args: --timeout=10m --out-format=colored-line-number
