name: Check

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - example/**
      - "**/*.md"
      - "**/*.yaml"
  push:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: 🧹 Lint
        uses: golangci/golangci-lint-action@v4
